version: "3.8"
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./.env.local
    # environment:
    #   - VITE_BACKEND_URL=http://backend:5000
